
PLUGINS.onPush = function(docStack) {
  var newEntry = {pluginVar: 'Generated by JS code'};
  print(docStack.debugString());
  if (docStack.get('pretty')) {
    newEntry['include-js'] = 'http://www/foo/pretty.js';
  }
  return newEntry;
}
